.DEFAULT: all
all: 
	cd ffi && $(MAKE)
	cd fib && $(MAKE)
	cd generic-record && $(MAKE)
	cd greet && $(MAKE)
	cd haversine && $(MAKE)
	cd hello-world && $(MAKE)
	cd identity && $(MAKE)
	cd memory && $(MAKE)
	cd named-argument && $(MAKE)
	cd record && $(MAKE)
	cd union && $(MAKE)

.PHONY: clean
clean:
	cd ffi && $(MAKE) clean
	cd fib && $(MAKE) clean
	cd generic-record && $(MAKE) clean
	cd greet && $(MAKE) clean
	cd haversine && $(MAKE) clean
	cd hello-world && $(MAKE) clean
	cd identity && $(MAKE) clean
	cd memory && $(MAKE) clean
	cd named-argument && $(MAKE) clean
	cd record && $(MAKE) clean
	cd union && $(MAKE) clean
