graph TB
    Text[Source Text] -->|Parsing| CST
    CST --> |Module resolution|RCST
    RCST --> OAST
    RCST --> |Macroexpansion|RCST
    OAST --> |Alpha renaming|Alpha
    Alpha --> AST
    AST --> DAST
    AST --> |Type checking|TAST
    DAST --> |Type checking|TAST
    TAST --> |Linarity checking|TAST
    TAST --> |Monomorphization|MTAST
    MTAST --> |Monomorph expansion|EMTAST
    EMTAST --> HIR
    HIR --> |Data linearization|MIR
    MIR --> |Flow linearization|LIR
    LIR --> LLVM
