name: Build on MacOS
on:
  # Only build when merging a PR or pushing to master.
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: true

    runs-on:
      - macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.1

      - name: install ocaml dependencies
        run: opam install --deps-only -y .

      - name: embed builtins
        run: make lib/BuiltInModules.ml

      - name: build
        run: opam exec dune build

      - name: upload compiler binary
        uses: actions/upload-artifact@v2
        with:
          name: austral-macos-bin
          path: austral
          retention-days: 1