name: Build on MacOS
on:
  - push

jobs:
  build:
    strategy:
      fail-fast: true

    runs-on:
      - macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.1

      - name: install ocaml dependencies
        run: opam install --deps-only -y .

      - name: embed builtins
        run: make lib/BuiltInModules.ml

      - name: build
        run: opam exec dune build