name: Build on MacOS
on:
  - push

jobs:
  build-and-test-linux:
    strategy:
      fail-fast: true

    runs-on:
      - macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0

      - name: install ocaml dependencies
        run: opam install --deps-only -y .