name: Build on MacOS
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: true

    runs-on:
      - macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.0

      - name: build
        run: |
          set -x

          opam switch create austral 4.13.0
          eval $(opam env --switch=austral --set-switch)
          opam install --deps-only -y .

          make

          cd standard
          make

      - name: upload compiler binary
        uses: actions/upload-artifact@v4
        with:
          name: austral-macos-bin
          path: austral
          retention-days: 1
